# Generated by Django 5.2.17 on 2026-09-28 11:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.TextField()),
                ('difficulty', models.CharField(choices=[('Very easy', 'Very easy'), ('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Difficult', 'Difficult'), ('Very difficult', 'Very difficult')], max_length=20)),
                ('time_required_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tools', models.TextField(blank=True, help_text='Satu alat per baris.')),
                ('ifixit_guideid', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_guides', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_guides', to='devices.device')),
            ],
            options={
                'ordering': ['title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SafetyWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('caution', 'Perhatian'), ('danger', 'Bahaya')], max_length=10)),
                ('message', models.TextField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='guides.repairguide')),
            ],
        ),
        migrations.CreateModel(
            name='GuideStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='guides.repairguide')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('guide', 'order'), name='unique_guide_step_order')],
            },
        ),
    ]
